'''finbert.py – sentiment inference using Hugging Face FinBERT

This module reads the processed news Parquet file (generated by the
preprocessing stage), runs a **FinBERT** sentiment pipeline, and writes the
results to ``data/processed/sentiment.parquet``. It also logs a simple
metric (average positive confidence) with **DVCLive** so the experiment can
be reproduced and tracked.

Typical usage::

    from src.sentiment.finbert import run_sentiment
    run_sentiment()

Running the module as a script (`python -m src.sentiment.finbert`) will also
execute the pipeline.
''' 

from __future__ import annotations

from pathlib import Path
from typing import List

import polars as pl
from transformers import pipeline, Pipeline
from dvclive import Live

from src.utils.paths import PROCESSED_DATA_DIR, METRICS_DIR
from src.utils.logger import get_logger
from src.utils.config import load_config

LOGGER = get_logger(__name__)

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def _load_processed_news(input_path: Path) -> pl.DataFrame:
    """Load the processed news parquet file.

    Parameters
    ----------
    input_path: Path
        Path to the parquet file containing cleaned news.
    """
    LOGGER.debug("Reading processed news parquet", extra={"path": str(input_path)})
    return pl.read_parquet(input_path)


def _init_pipeline() -> Pipeline:
    """Create a Hugging Face sentiment pipeline for FinBERT.

    The model ``ProsusAI/finbert`` is a common public checkpoint for
    financial sentiment analysis. The pipeline is lazy‑loaded; the actual
    model download happens only on the first call.
    """
    LOGGER.info("Initializing FinBERT sentiment pipeline")
    return pipeline(
        "sentiment-analysis",
        model="ProsusAI/finbert",
        tokenizer="ProsusAI/finbert",
        truncation=True,
        device=0,  # assumes a GPU is available; fallback to CPU automatically
    )


def _run_batch(p: Pipeline, texts: List[str]) -> List[dict]:
    """Run the pipeline on a list of texts.

    The pipeline returns a list of dictionaries with ``label`` and ``score``.
    """
    return p(texts)


def _add_sentiment_columns(df: pl.DataFrame, results: List[dict]) -> pl.DataFrame:
    """Append ``sentiment_label`` and ``sentiment_score`` columns.

    ``results`` must be in the same order as ``df`` rows.
    """
    labels = [r["label"] for r in results]
    scores = [float(r["score"]) for r in results]
    df = df.with_columns([
        pl.Series("sentiment_label", labels),
        pl.Series("sentiment_score", scores),
    ])
    return df

# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def run_sentiment(
    input_path: Path | None = None,
    output_path: Path | None = None,
    metrics_path: Path | None = None,
) -> Path:
    """Run FinBERT sentiment analysis on processed news.

    Parameters
    ----------
    input_path: optional Path
        Path to the processed news parquet. Defaults to
        ``PROCESSED_DATA_DIR / "news.parquet"``.
    output_path: optional Path
        Destination for the sentiment results parquet. Defaults to
        ``PROCESSED_DATA_DIR / "sentiment.parquet"``.
    metrics_path: optional Path
        Directory where DVCLive will write its ``metrics.csv``. Defaults to
        ``METRICS_DIR / "sentiment"``.

    Returns
    -------
    Path
        Path to the written sentiment parquet file.
    """
    cfg = load_config()
    LOGGER.info(
        "Starting sentiment pipeline",
        extra={"batch_size": cfg.batch_size, "seed": cfg.seed},
    )

    inp = input_path or PROCESSED_DATA_DIR / "news.parquet"
    out = output_path or PROCESSED_DATA_DIR / "sentiment.parquet"
    metrics_dir = metrics_path or METRICS_DIR / "sentiment"
    metrics_dir.mkdir(parents=True, exist_ok=True)

    df = _load_processed_news(inp)
    if df.is_empty():
        LOGGER.warning("Processed news file is empty; exiting sentiment step")
        return out

    # The column containing the article text – we standardised it to ``content``
    # during preprocessing.
    if "content" not in df.columns:
        raise KeyError("Column 'content' not found in processed data")
    texts = df["content"].to_list()

    # Initialise pipeline (model will be cached on first run)
    sentiment_pipe = _init_pipeline()

    # Run inference in batches for memory‑efficiency.
    batch_size = cfg.batch_size
    results: List[dict] = []
    for i in range(0, len(texts), batch_size):
        batch_texts = texts[i : i + batch_size]
        batch_res = _run_batch(sentiment_pipe, batch_texts)
        results.extend(batch_res)
        LOGGER.debug(
            "Processed batch",
            extra={"batch_start": i, "batch_end": i + len(batch_texts)},
        )

    df_sent = _add_sentiment_columns(df, results)

    # Write Parquet output
    out.parent.mkdir(parents=True, exist_ok=True)
    df_sent.write_parquet(out)
    LOGGER.info("Sentiment results written", extra={"rows": df_sent.height, "path": str(out)})

    # -------------------------------------------------------------------
    # DVCLive metrics – we log the mean positive confidence. FinBERT uses
    # three labels: ``positive``, ``negative`` and ``neutral``. For a quick
    # health check we compute the average score for the *positive* label.
    # -------------------------------------------------------------------
    with Live(metrics_dir) as live:
        # Extract scores for rows labelled "positive"
        pos_scores = [r["score"] for r in results if r["label"].lower() == "positive"]
        avg_pos = sum(pos_scores) / len(pos_scores) if pos_scores else 0.0
        live.log_metric("avg_positive_score", avg_pos)
        live.log_metric("total_rows", df_sent.height)
        LOGGER.info(
            "DVCLive metrics logged",
            extra={"avg_positive_score": avg_pos, "total_rows": df_sent.height},
        )

    return out


if __name__ == "__main__":
    # Simple CLI entry point for quick repro
    out_path = run_sentiment()
    LOGGER.info("Sentiment pipeline completed", extra={"output": str(out_path)})
