source: yfinance
tickers:
- CVX
- XOM
- TSLA
- ARKX
- SMH
- JEDI
- LMT
use_rolling_window: true
rolling_days: 365
start_date: '2025-06-14'
end_date: '2026-06-14'
partition_freq: month
compression: zstd
default_sentiment_ticker: MARKET
